package com.example.medideals.utils

object Constants
{
    val MESSAGE = "message"
    val PRODUCT_ID = "product.id"
    val PRODUCT_QUANTITY = "product.qty"
    val DEVICE_ID = "10"
    val VENDOR_ID = "26"
    val PRODUCT_NAME = "product_name"
    val PRODUCT_DETAIL = "product.detail"
    val USER_ID = "user.id"
    val INFO_DATA = "info.data"
    val HOME = "home"
    val HOME_ACTIVITY = "home.act"
    val PROFILE_TYPE = "profile.type"
    val PHONE_NUMBER = "ph.num"
    val GO_TO_CART = "cart"
    val VIEW_CART = "view_cart"
    val DEVICE_TYPE = "2"
    val SCREEN = "screen"
    val LOGIN_TYPE = "login.type"
    val REGISTER_TYPE = "register.type"
    val LOGOUT = "logout"
    val EDIT_DOC_NUM = "edit.doc.num"
    val CHANGE_ORDER_STATUS = "change.order.status"
    val PRODUCT_INFO = "product.info"
    val COUNTRYCODE_INDIA = "+91"
    val TOTAL_LISTED_PRODUCTS = "total.lis.prod"
    val TOTAL_ORDERS_RECEIVED = "total.orders.rec"
    val TOTAL_PRODUCTS_RECEIVED = "total.prod.rec"
    val TOTAL_ORDERS_RECEIVED_BUY = "total.orders.rec.buy"
    val TOTAL_ORDERS_DISPATCH = "total.orders.disp"
    val TOTAL_ORDERS_DELIVERED = "total.orders.del"
    val TOTAL_ORDERS_RETURN = "total.orders.return"
    val TOTAL_PRODUCTS_RETURN = "total.prod.return"
    val TOTAL_ORDERS_RETURN_BUY = "total.orders.return.buy"
    val TOTAL_ORDERS_PLACED = "total.orders.placed"
    val ORDERS_PLACED = "orders.placed"
    val TOTAL_ACTIVE_PRODUCTS = "total.activ.prod"
    val TOTAL_INACTIVE_PRODUCTS = "total.inactiv.prod"
    val ORDER_RECEIVED = "order.rec"
    val LAST_ORDER = "last.order"
    val TITLE_CATEGORY = "title.cat"
    val CATEGORY_ID = "cat.id"
    val ALLOPATHIC_TYPE = "allopathic"
    val SEARCH_QUERY = "search.query"
    val CHECKOUT_TYPE = "checkout.type"
    val TOTAL_AMOUNT = "total.amt"
    val TOTAL_ITEMS = "total.items"
    val EMAIL = "email"
    var ALLOPATHIC_DATA = "allopathic.data"


}